version: '3.10'

services:

  nginx:
    image: docker-nginx:latest
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static:/app/static
    depends_on:
      - fastapi-app

  fastapi-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastapi-db
      POSTGRES_PASSWORD: 123

volumes:
  static: