"""Fix picture id

Revision ID: 327b2066c1db
Revises: fdcba75b31c4
Create Date: 2022-05-10 20:03:42.616160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "327b2066c1db"
down_revision = "fdcba75b31c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post_pictures", sa.Column("id", sa.BIGINT(), nullable=False))
    op.drop_column("post_pictures", "post_picture_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post_pictures", sa.Column("post_picture_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column("post_pictures", "id")
    # ### end Alembic commands ###
