"""Add first migration

Revision ID: 43bae35c89aa
Revises: 
Create Date: 2022-05-22 17:56:25.839944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43bae35c89aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cryptocurrencies",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("symbol", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("crypto_info", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "exchanges",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("year_established", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("trust_score", sa.BIGINT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("is_google", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "coin_price",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("coin_id", sa.BIGINT(), nullable=True),
        sa.Column("exchange_id", sa.BIGINT(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("time", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["cryptocurrencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_favourite_cryptos",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("coin_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["cryptocurrencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "likes",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_pictures",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.Column("picture_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_topics",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.Column("coin_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["cryptocurrencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts_comments",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.Column("data", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts_comments")
    op.drop_table("post_topics")
    op.drop_table("post_pictures")
    op.drop_table("likes")
    op.drop_table("users_favourite_cryptos")
    op.drop_table("posts")
    op.drop_table("coin_price")
    op.drop_table("users")
    op.drop_table("exchanges")
    op.drop_table("cryptocurrencies")
    # ### end Alembic commands ###
