"""Add is admin and post topics

Revision ID: de6eaf7cc8e4
Revises: 327b2066c1db
Create Date: 2022-05-15 16:30:48.086539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de6eaf7cc8e4"
down_revision = "327b2066c1db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_topics",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.Column("coin_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["cryptocurrencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.drop_table("post_topics")
    # ### end Alembic commands ###
